In [4]:
import pandas as pd

## Series

In [14]:
a = s = [10,20,30,40]
a1 = pd.Series(a)
a1

0    10
1    20
2    30
3    40
dtype: int64

In [18]:
b = [100,200,300]
b1 = pd.Series(b, index = ['a', 'b', 'c'])
b1

a    100
b    200
c    300
dtype: int64

In [20]:
b1[0]

C:\Users\Dell Latitude 3470\AppData\Local\Temp\ipykernel_13356\1165840123.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b1[0]

100

In [22]:
b1['a']

100

In [30]:
marks = {
    "math" : 85,
    "science" : 78,
    "english" : 92,
    "history": 74,
    "art": 88
}
marks1 = pd.Series(marks)
marks1

math       85
science    78
english    92
history    74
art        88
dtype: int64

In [32]:
marks["math"]

85

In [36]:
marks1[0]

C:\Users\Dell Latitude 3470\AppData\Local\Temp\ipykernel_13356\1941606896.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks1[0]

85

In [44]:
marks1 + 5

math       90
science    83
english    97
history    79
art        93
dtype: int64

In [46]:
marks1 * 2

math       170
science    156
english    184
history    148
art        176
dtype: int64

In [48]:
marks1 / 2

math       42.5
science    39.0
english    46.0
history    37.0
art        44.0
dtype: float64

In [50]:
marks1 ** 2

math       7225
science    6084
english    8464
history    5476
art        7744
dtype: int64

In [60]:
marks1 > 80

math        True
science    False
english     True
history    False
art         True
dtype: bool

In [66]:
marks1 == 85

math        True
science    False
english    False
history    False
art        False
dtype: bool

In [68]:
marks1[marks1 > 80]

math       85
english    92
art        88
dtype: int64

In [71]:
c1 = pd.Series([1, 2, 3])
c2 = pd.Series([10, 20, 30])
c1 + c2

0    11
1    22
2    33
dtype: int64

In [73]:
c1 * c2

0    10
1    40
2    90
dtype: int64

In [77]:
c1.sum()

6

In [79]:
c1.mean()

2.0

In [81]:
c1.max()

3

In [83]:
c1.min()

1

In [85]:
c1.count()

3

In [91]:
c1.std()

1.0

In [93]:
c1.isnull()

0    False
1    False
2    False
dtype: bool

In [99]:
c1.replace(1,100)

0    100
1      2
2      3
dtype: int64

In [101]:
c1.sort_values()

0    1
1    2
2    3
dtype: int64

In [103]:
c1.unique()

array([1, 2, 3], dtype=int64)

## DATAFRAME

In [114]:
data = {
    'Name':['Ali','Sara', 'Ahmed'],
    'Age':[20,22, 21],
    'marks': [80, 95, 70]
}

df = pd.DataFrame(data)
df

    Name  Age  marks
0    Ali   20     80
1   Sara   22     95
2  Ahmed   21     70

In [124]:
data1 = [
    ['Ali','Sara', 'Ahmed'],
    [20,22, 21],
    [80, 95, 70]
]
df = pd.DataFrame(data1, columns=['Name', 'Age', 'Marks'])
df

  Name   Age  Marks
0  Ali  Sara  Ahmed
1   20    22     21
2   80    95     70

In [126]:
df.head()

  Name   Age  Marks
0  Ali  Sara  Ahmed
1   20    22     21
2   80    95     70

In [128]:
df.tail()

  Name   Age  Marks
0  Ali  Sara  Ahmed
1   20    22     21
2   80    95     70

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      object
 2   Marks   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [136]:
df.shape

(3, 3)

### Practice 2
- Create a DataFrame with:
-   Student Name
-   Subject
-   Marks
-   (Add at least 4 students)

In [161]:
data = {
    'name':['Ali','Sara', 'Ahmed', 'Zain'],
    'subject':['math','physics', 'computer science', 'history'],
    'marks': [80, 95, 70, 80]
}

df = pd.DataFrame(data, index = ['a', 'b', 'c', 'd'])
df

    name           subject  marks
a    Ali              math     80
b   Sara           physics     95
c  Ahmed  computer science     70
d   Zain           history     80

In [163]:
df.columns

Index(['name', 'subject', 'marks'], dtype='object')

In [165]:
df['name']

a      Ali
b     Sara
c    Ahmed
d     Zain
Name: name, dtype: object

In [167]:
df[['name', 'marks']]

    name  marks
a    Ali     80
b   Sara     95
c  Ahmed     70
d   Zain     80

In [173]:
# loc is labled based
df.loc['a']

name        Ali
subject    math
marks        80
Name: a, dtype: object

In [177]:
# iloc is positional based
df.iloc[0]

name        Ali
subject    math
marks        80
Name: a, dtype: object

### PRACTICE 3:
1. Print only Marks column
2. Print first row
3. Print marks of first student

In [191]:
df.loc[:,'marks']

a    80
b    95
c    70
d    80
Name: marks, dtype: int64

In [193]:
df.iloc[0]

name        Ali
subject    math
marks        80
Name: a, dtype: object

In [199]:
df.loc['a', 'marks']

80

### Add Column

In [237]:
df['total'] = df['marks'] + 5

In [239]:
df

    name           subject  marks  total
a    Ali              math     80     85
b   Sara           physics     95    100
c  Ahmed  computer science     70     75
d   Zain           history     80     85

### Remove Column
- axis=1 → column
- axis=0 → row

In [247]:
df.drop('total', axis=1, inplace=True, errors='ignore')

In [ ]:
df.drop('d', axis=0, inplace=True, errors='ignore')

In [253]:
df

    name           subject  marks  total
a    Ali              math     80     85
b   Sara           physics     95    100
c  Ahmed  computer science     70     75

In [255]:
import numpy as np

In [339]:
data2 = {
    'name' : ['anas', 'talha', 'zaid'],
    'mark' : [76, 96, np.nan]
}
df = pd.DataFrame(data2)
df

    name  mark
0   anas  76.0
1  talha  96.0
2   zaid   NaN

In [341]:
# Detect Missing
df.isnull()

    name   mark
0  False  False
1  False  False
2  False   True

In [343]:
df.isnull().sum() # give the sum of null value of given column

name    0
mark    1
dtype: int64

In [285]:
df.dropna() # Removes rows containing missing values.

    name  mark
0   anas  76.0
1  talha  96.0

In [345]:
df.fillna(0) # Fill missing data
df.loc[0, 'mark'] = np.nan

    name  mark
0   anas   NaN
1  talha  96.0
2   zaid   NaN

In [351]:
df['mark'] = df['mark'].fillna(df['mark'].mean())

In [353]:
df

    name  mark
0   anas  96.0
1  talha  96.0
2   zaid  96.0