## Name: Muhammad Anas Rizwan
## Topic: Pandas

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
file_path = '/content/drive/MyDrive/Colab_Notebooks/data_Iris.csv'

data = pd.read_csv(file_path, delimiter=',', )
print(data.head())

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
print(data.tail())

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

In [7]:
data.shape

(150, 5)

In [8]:
print(data.describe())

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
data.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [10]:
data['Species'].head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: Species, dtype: object

In [11]:
data.loc[0:5]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa

In [12]:
data.iloc[0:5]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
data.loc[0:"Sepal.Length"]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [18]:
data[data['Species'] == "setosa"].head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [19]:
data[data["Sepal.Length"] > 5].head()

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0            5.1          3.5           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa

In [20]:
data["sepal_area"] = data["Sepal.Length"] * data["Sepal.Width"]
data

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,sepal_area
0,5.1,3.5,1.4,0.2,setosa,17.85
1,4.9,3.0,1.4,0.2,setosa,14.70
2,4.7,3.2,1.3,0.2,setosa,15.04
3,4.6,3.1,1.5,0.2,setosa,14.26
4,5.0,3.6,1.4,0.2,setosa,18.00
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10
146,6.3,2.5,5.0,1.9,virginica,15.75
147,6.5,3.0,5.2,2.0,virginica,19.50
148,6.2,3.4,5.4,2.3,virginica,21.08
149,5.9,3.0,5.1,1.8,virginica,17.70

In [21]:
data.drop("sepal_area", axis=1, inplace=True)

In [22]:
data

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
data.dropna() # removes missing values
data.dropna(subset=["Sepal.Length"] ) # it will remove that row with missing Speal.Length is removed.

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [23]:
data.isnull().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [24]:
data.sort_values("Sepal.Length")

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
8             4.4          2.9           1.4          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [25]:
data.sort_values("Sepal.Length", ascending=False)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
131           7.9          3.8           6.4          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [37]:
# loc[row, column]
data.loc[0, "Sepal.Length"] = 100
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0         100.0          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [35]:
data[data["Sepal.Length"] == 100]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0         100.0          3.5           1.4          0.2  setosa

In [38]:
data.loc[0:4]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0         100.0          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
a=data.loc[[0,0,1,1]]
a.duplicated()

0    False
0     True
1    False
1     True
dtype: bool

In [40]:
data.duplicated().value_counts()

False    147
True       3
Name: count, dtype: int64

In [41]:
# To show the duplicated value. note previous row is same as next row
data[data.duplicated()]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
34            4.9          3.1           1.5          0.1     setosa
37            4.9          3.1           1.5          0.1     setosa
142           5.8          2.7           5.1          1.9  virginica

In [43]:
# To remove the duplicated values.
data.drop_duplicates().head(10)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0         100.0          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [44]:
# To check how many rows are removed.
print("Before:",data.shape)
data = data.drop_duplicates()
print("After:",data.shape)

Before: (150, 5)
After: (147, 5)

## Practice
1. Show first 10 rows
2. Show petal_length column
3. Filter rows where species = "versicolor"
4. Create Petal_area column
5. Sort by petal_width descending
6. Show average sepal_length

In [45]:
data.head(5)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0         100.0          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [47]:
data["Petal.Length"].head()

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: Petal.Length, dtype: float64

In [48]:
data[data['Species'] == "versicolor"].head()

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [51]:
data["Petal.Area"] = data["Petal.Length"] * data["Petal.Width"]
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  Petal.Area
0         100.0          3.5           1.4          0.2  setosa        0.28
1           4.9          3.0           1.4          0.2  setosa        0.28
2           4.7          3.2           1.3          0.2  setosa        0.26
3           4.6          3.1           1.5          0.2  setosa        0.30
4           5.0          3.6           1.4          0.2  setosa        0.28

In [52]:
data.sort_values("Petal.Width", ascending=False)

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Petal.Area
100,6.3,3.3,6.0,2.5,virginica,15.00
144,6.7,3.3,5.7,2.5,virginica,14.25
109,7.2,3.6,6.1,2.5,virginica,15.25
114,5.8,2.8,5.1,2.4,virginica,12.24
140,6.7,3.1,5.6,2.4,virginica,13.44
...,...,...,...,...,...,...
39,5.1,3.4,1.5,0.2,setosa,0.30
12,4.8,3.0,1.4,0.1,setosa,0.14
13,4.3,3.0,1.1,0.1,setosa,0.11
9,4.9,3.1,1.5,0.1,setosa,0.15
32,5.2,4.1,1.5,0.1,setosa,0.15

In [53]:
data['Sepal.Length'].mean()

np.float64(6.50204081632653)

In [54]:
data.groupby("Species").mean()

            Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Petal.Area
Species
setosa          6.987500     3.431250      1.462500     0.250000    0.371667
versicolor      5.936000     2.770000      4.260000     1.326000    5.720400
virginica       6.604082     2.979592      5.561224     2.028571   11.328980

In [55]:
# Aggregation functions are functions that combine multiple values into one single value.
# So one group -> multiple summary results.
data.groupby("Species").agg(["max", "min", "mean"])

           Sepal.Length                Sepal.Width                 \
                    max  min      mean         max  min      mean
Species
setosa            100.0  4.3  6.987500         4.4  2.3  3.431250
versicolor          7.0  4.9  5.936000         3.4  2.0  2.770000
virginica           7.9  4.9  6.604082         3.8  2.2  2.979592

           Petal.Length                Petal.Width                Petal.Area  \
                    max  min      mean         max  min      mean        max
Species
setosa              1.9  1.0  1.462500         0.6  0.1  0.250000       0.96
versicolor          5.1  3.0  4.260000         1.8  1.0  1.326000       8.64
virginica           6.9  4.5  5.561224         2.5  1.4  2.028571      15.87


             min       mean
Species
setosa      0.11   0.371667
versicolor  3.30   5.720400
virginica   7.50  11.328980

In [56]:
data["Species"].value_counts()

Species
versicolor    50
virginica     49
setosa        48
Name: count, dtype: int64

# Pivot Tables

For summaring data, short summary table

In [60]:
# pd.pivot_table(data, values="Sepal.Length", index="Species", aggfunc="mean")
data.pivot_table(values="Sepal.Length", index="Species", aggfunc="mean")

            Sepal.Length
Species
setosa          6.987500
versicolor      5.936000
virginica       6.604082

In [61]:
# values->calculate value
data.pivot_table(values="Sepal.Length", index="Species", aggfunc=["mean", "nunique"])

                   mean      nunique
           Sepal.Length Sepal.Length
Species
setosa         6.987500           16
versicolor     5.936000           21
virginica      6.604082           21